"""Summarize GRACE scores from workbook + grace_expansion.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "configs/annotations/manual_phase1.json"
EXPANSION = ROOT / "configs/evaluation/grace_expansion.json"
OUT = ROOT / "docs/GRACE_SUMMARY.md"

DIMS = ["interpretability", "actionability", "nuance", "redundancy"]


def main() -> None:
    scores = {d: [] for d in DIMS}
    n_fp = n_tp = 0

    wb = json.loads(WORKBOOK.read_text(encoding="utf-8"))
    for ex in wb["excerpts"]:
        for c in ex.get("comparisons", []):
            g = c.get("grace")
            if not g:
                continue
            for d in DIMS:
                if d in g:
                    scores[d].append(g[d])
            if c.get("triangulation") == "silence" and c.get("manual_id") is None:
                n_fp += 1
            else:
                n_tp += 1

    if EXPANSION.exists():
        for item in json.loads(EXPANSION.read_text()).get("items", []):
            g = item.get("grace", {})
            for d in DIMS:
                if d in g:
                    scores[d].append(g[d])
            n_tp += 1

    n = len(scores["interpretability"])
    lines = [
        "# GRACE summary (expanded sample)",
        "",
        f"**n = {n}** (workbook comparisons + `configs/evaluation/grace_expansion.json`)",
        "",
        "| Dimension | Mean (1–5) |",
        "|-----------|------------|",
    ]
    for d in DIMS:
        vals = scores[d]
        mean = sum(vals) / len(vals) if vals else 0
        lines.append(f"| {d.capitalize()} | {mean:.2f} |")

    lines.extend(
        [
            "",
            f"**Subset:** {n_tp} agreement/true-positive style · {n_fp} false-positive (silence, LLM-only)",
            "",
            "*Generated by `scripts/summarize_grace.py`*",
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} (n={n})")


if __name__ == "__main__":
    main()
